### ISSUE TITLE
Pretend that text is shorter than it actually is

### ISSUE THREAD

**Issue by cocreature** [quchen/prettyprinter#11]
I’m rendering text that I know will only be viewed in editors that use some sort of pretty symbols mode that replaces certain words by their unicode equivalents (e.g. `forall` is displayed as `∀`). Therefore I’de like indentation to treat `forall` like a single character. Currently, I just use the internal `Text` constructor to do so and it works just fine but based on our discussion it seems like this is actually a safe operation so it would be nice if this was possible without resorting to internals.

**Comment by quchen** [comment]
Good point, I did not consider this. I don’t think anything goes wrong if you just hack this together yourself using the internals of `Doc`, but that’s hardly best practice.

The use case is valid, but I don’t see a straightforward way to implement this other than in an ad-hoc way. Sure, we can define

```haskell
shortText :: Int -> Text -> Doc ann
shortText = Text
```

which allows us to *define* the length of the contained text as far as the layouter is concerned, but this just begs the question why we can’t define the length of e.g. `pretty 't' <> "ext"` be 2? In order to achieve this, we’d have to generalize our definition to

```haskell
overrideWidth :: Int -> Doc ann -> Doc ann
```

but that gives us another problem: a `Doc` does not have a width per se, the layouter inserts breaks and indentation to match the page constraints, and doing so tries different versions until one fits.

I’m afraid for now you’ll have to use your hack, but maybe I can come up with a better suggestion in the next couple of days. If not, you know how to nag me on IRC ;-)

**Comment by quchen** [comment]
One way of implementing this would be by adding a new `Doc` constructor,

```haskell
data Doc ann
    = …
    | AlterWidth (Int -> Int) (Doc ann)
    …
```
that is rendered as
```
AlterWidth f x -> let !cc' = f cc in best nl cc' x
```
but this would break if we have multiline contents, something very common. I don’t think this can be implemented in a robust way, and the use case seems not that common. In the end, this boils down to supporting non-monospaced fonts, and the algorithm wasn’t made for that.

**Comment by quchen** [comment]
Closing as won’t fix, since I don’t know how to implement this. I’m not against the feature itself though, just against an ad-hoc version of it.
