### ISSUE TITLE
Backpack for underlying string representation

### ISSUE THREAD

**Issue by minad** [quchen/prettyprinter#16]
I wanted to try that for a while now in wl-pprint-annotated. Might just be interesting as an experiment.

**Comment by quchen** [comment]
I don't think there is anything to be gained for the library here. Why would we switch out the underlying representation?

**Comment by minad** [comment]
Well you switched from String to Text for some reason ;)

There is also foundation relying only on its own string types.

I mean this could just be nice to explore how backpack works in the given context since I've seen it promoted as a solution to the string problem.

**Comment by quchen** [comment]
- I switched to `Text` since `String` is wrong, and only exists for historical reasons.
- I want to maintain backwards compatibility with at least the last 3 major GHC releases, and Backpack is not even in the current major release.

For testing Backpack, I think a much smaller (minimal) example could achieve the same learning benefits – like `data Doc = Text text | Cat Doc Doc`.
