### ISSUE TITLE
Make available via Stackage

### ISSUE THREAD

**Issue by NickMcAvoy** [quchen/prettyprinter#18]
I'd love to make use of this library, but unless I'm mistaken it's not currently available via the Haskell Stack. From [the project's page](https://www.stackage.org/package/prettyprinter) on Stackage:

> This package is not currently in any snapshots. If you're interested in using it, we recommend adding it to Stackage Nightly. Doing so will make builds more reliable, and allow stackage.org to host generated Haddocks.

**Comment by quchen** [comment]
I'm planning to wait for another week or so, and then releasing 1.0 and adding that to Stackage. Until then, you can already use it by adding it to your extra-deps in stack.yaml :-)

**Comment by quchen** [comment]
By the way, the reason I haven’t released it on Stackage yet is that Stackage does not do any major version bumps in an LTS release. Since I was planning to (potentially) make a couple of minor breaking changes in the preview versions (< version 1), adding 0.x to Stack would have meant that the fixes might not be available for half a year (when the new LTS is released). But I’m fairly happy with the library now, so that nothing really stands in the way of making the 1.0 release, with fanfares, Reddit, Stackage and what not.

**Comment by NickMcAvoy** [comment]
I guess I caught you on the cusp! That's good to know. Thanks for the `extra-deps` tip; I'll look forward to the release. Congratulations on 1.0!

**Comment by quchen** [comment]
The ticket is valid! Let's leave it open until it's actually there.
