### ISSUE TITLE
Identity element for vertical concatenation

### ISSUE THREAD

**Issue by expipiplus1** [quchen/prettyprinter#56]
It would be nice to have a zero height element to use as an identity when vertically appending Docs.

**Comment by quchen** [comment]
It would! The only problem with this is that the Doc type does not support vertical concatenation – verticality is a line followed by a newline followed by another line, kind of like "foo\nbar". Since the "\n" is inserted when using vcat unconditionally, there is currently no way to have an identity element without modifying the Doc type for this special case.

For the time being you’ll have to remove the elements of `vcat`’s argument list manually if you don’t want them rendered.

If you have an idea how to implement this I’m open to a pull request for it, as long as the code change is comparable to the (small) utility of such a thing.

**Comment by expipiplus1** [comment]
I thought this might be the case, thanks for the thoughtful response!
