### ISSUE TITLE
more performance tests (looking good, but 'align' is expensive)

### ISSUE THREAD

**Issue by jwaldmann** [quchen/prettyprinter#58]
Hi, just FYI,

I just added `prettyprinter` to https://github.com/jwaldmann/pretty-test which enumerates and iterates contexts, in order to find documents that are hard to render. 

On the subset of combinators that this test uses - it's looking good! `prettyprinter` beats `pretty`, and both are fast. The `wl-*` libs still seem to have problems.

See output at https://travis-ci.org/jwaldmann/pretty-test/jobs/373884017 Well, it's timing data on travis, but still. Also confirmed on a local idle machine.

But `align` is expesive? Look at this (10 seconds in ghci)
```
import Data.String
import Data.Text.Prettyprint.Doc
import Data.Text.Prettyprint.Doc.Render.Text

renderLazy  $ layoutPretty defaultLayoutOptions  $ iterate ( \ hole ->  align $ sep [sep [hole], sep []] ) (fromString  "l") !! 500
```

**Comment by quchen** [comment]
Woah that’s a pretty cool test, thank you for doing it! I wouldn’t know how to improve `align` though, [the source is already fairly succinct](http://hackage.haskell.org/package/prettyprinter-1.2.0.1/docs/src/Data-Text-Prettyprint-Doc-Internal.html#align).

What happens when you use `layoutSmart` or `layoutCompact` instead of `layoutPretty`? Maybe this is something that is rooted in the layout algorithm. If that made a big difference it would narrow down where to look for the performance sink. (I expect time(layoutCompact) < time(layoutPretty) < time(layoutSmart).)

**Comment by jwaldmann** [comment]
now there's a choice of layout methods: https://github.com/jwaldmann/pretty-test/commit/408d02b3b680c5d85fc8483903a168da9d56b42b

indeed, "compact" is super snappy, while "smart" is not much more expensive than "pretty".

**Comment by jwaldmann** [comment]
... but it could traversed twice (and, by recursion, much more often)?

**Comment by quchen** [comment]
The ticket remains valid (just tested your example), but since I haven’t heard of real use cases where deeply nested aligns were encountered and this has become a problem, I’m closing this now.
If interest to work on this comes up again, we can open a new ticket, but I suspect the fix will be nontrivial.
