### ISSUE TITLE
ByteString instances?

### ISSUE THREAD

**Issue by clinty** [quchen/prettyprinter#61]
I'm attempting to convert from wl-pprint-extras and the lack of Pretty ByteString means I can't automatically derive Pretty for ByteString newtypes.  Is this intentional?  Should I just hand-write the instances?

**Comment by quchen** [comment]
That’s intentional.

Right now the library does not depen on Bytestring, so adding the instances would require adding another dependency just for these instances. And then Bytestring has another problem: they don’t have any inherent meaning, so what should the default Pretty instance be – assume Unicode, print as hexdump?
