### ISSUE TITLE
Peeking at the document annotation?

### ISSUE THREAD

**Issue by wiz** [quchen/prettyprinter#62]
I want to carry some rendering-relevant information inside the document itself and would like to have a `Doc ann -> Maybe ann` which would give the annotation if the immediate outer layer of the argument is Annotation.
I did that using published Internals (thanks for making it available!) but were surprised to find only setting/altering functions in the public API.

**Comment by quchen** [comment]
What do you mean with »immediate outer layer of the argument«? `Annotated () "foobar"` vs `Annotated () (Cat "foo" "bar")`?

I don’t want to make documents that render identically be different in any way, so either we make it possible to detect *all* annotations around a certain document (i.e. make the renderer know the current annotation stack), or not at all.

**Comment by wiz** [comment]
`Annotated ann (Doc ann)` vs any other constructor of `Doc ann`. Perhaps I'm abusing this mechanism but I need to pass some information to the upper wrapper so it could decide how this document should be treated.

**Comment by quchen** [comment]
Passing information down to prettyprinters of sub-elements is probably something the generator of the `Doc` should do, not the layouter built into the prettyprinter. An example where I used this was for a rainbow bracket highlighter, where each depth of parenthesation had a different color – instead of having the Doc look at the parent’s color, I had the Doc-generator keep track of the current level, adjusting it accordingly.

**Comment by wiz** [comment]
Indeed the annotations are a wrong place to keep stuff like this.
