### ISSUE TITLE
How to align two columns with respect to the maximum width of the element in the left column?

### ISSUE THREAD

**Issue by ChShersh** [quchen/prettyprinter#69]
First, I want to say thanks for implementing and maintaining such a great library! I'm really enjoying using it 🙂 But I have some difficulties implementing one aspect of pretty-printing and I wonder whether you can help me.

Let's say, I have the following two list of strings:

```haskell
l1 = ["foo", "person", "bar"]
l2 = ["baz", "address", "quux"]
```

I would like to format them as follows:

```haskell
foo    : baz
person : address
bar    : quux
```

But I can't find simple way to achieve this layouting with the `prettyprinter` library. Could you, please, help with this?

**Comment by quchen** [comment]
This is not easily solved, because the algorithm is (sadly) not suitable for column layouts.

`fill` and `fillBreak` are somewhat related, but they still require an explicit indentation parameter. You could get the width of a layouted document using `width` and then glue something together using those functions.

If you’ve got simple lists of text, you do

```haskell
l1 = ["foo", "person", "bar"]
l2 = ["baz", "address", "quux"]

maxLength = maximum (map length l1)
doc = zipWith (\key value -> fill maxLength (pretty key) <> " : " <> pretty value) l1 l2
```

but if your l1 consists of more complicated data, such as `Doc` instead of `Text`, this approach will become a bit hackier.

**Comment by ChShersh** [comment]
@quchen Thanks for the suggestion! I was expecting that something like that would be required. This resolves the issue for me :+1:
