### ISSUE TITLE
Bytestring Renderer

### ISSUE THREAD

**Issue by csasarak** [quchen/prettyprinter#79]
Would there be any interest in accepting a PR which outputs a Doc directly to a Bytestring?

**Comment by quchen** [comment]
Bytestrings don’t contain text, and this would be an additional dependency. I don’t think this is a good idea. Is there a sprecific use case you need this for?

**Comment by csasarak** [comment]
It is primarily for this PR I'm working on: https://github.com/tomjaguarpaw/haskell-opaleye/pull/436

We were looking at switching to `prettyprinter` for rendering SQL queries. The underlying library, `postgresql-simple` accepts a bytestring. For now, we render to `text` and then use `encodeUtf8` of the text library to turn it into a bytestring. I was going to see if it would be faster to turn a `SimpleDocStream` into a bytestring directly via the `Builder` interface instead of going to text and then to bytestring.

**Comment by quchen** [comment]
I see. Since using `Bytestring` is a quirk of `postgresql-simple` (which should really use `Text` I guess), I think the right place for the renderer would be in Opaleye. It’s not really a lot of code to write your own renderer (see e.g. the [`ShowS renderer`][shows]).

I’m not sure you’ll gain much performance in the process though, since Prettyprinter uses `Text` internally anyway. Writing your own renderer would have to convert the contained `Text` to `Bytestring` and then concatenate those, as opposed to simply rendering to one big `Text` value and then encoding that as a whole like in the straightforward solution.

[shows]: http://hackage.haskell.org/package/prettyprinter-1.3.0/docs/src/Data.Text.Prettyprint.Doc.Internal.html#renderShowS

**Comment by csasarak** [comment]
Thank you for that insight, I agree it probably doesn't make sense to do it that way anyhow. I'll close this.
